#spring.application.name=springclouddemo-zuul-gateway
#management.endpoints.jmx.exposure.include=*
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
## spring cloud access&secret config
## 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
#alibaba.cloud.access-key=****
#alibaba.cloud.secret-key=****
server:
  port: 6001
  servlet:
    context-path: /apigateway
#服务的名称
spring:
  application:
    name: zuul-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5060/eureka/eureka
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#自定义路由映射
zuul:
  routes:
    consumer-services: /zuulConsumer/**
    product-services: /zuulProduct/**
  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-services/**
  #忽略整个服务，对外提供接口
  ignored-services: consumer-services