#spring.application.name=springclouddemo-config
#management.endpoints.jmx.exposure.include=*
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
## spring cloud access&secret config
## 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
#alibaba.cloud.access-key=****
#alibaba.cloud.secret-key=****
#服务名称
server:
  port: 5001

#连接配置信息
spring:
  application:
    name: config-server-jdbc
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        default-label: dev
        jdbc:
          sql: SELECT akey , avalue FROM config_server where APPLICATION=? and APROFILE=? and LABEL=?
  #####################################################################################################
  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
#####################################################################################################

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5060/eureka/eureka